import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, query, orderBy, onSnapshot, doc, getDoc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { auth, db } from "/firebase-config.js";
import { collection as storageCollection, query as storageQuery, where as storageWhere, getDocs as storageGetDocs, addDoc as storageAddDoc, deleteDoc as storageDeleteDoc, doc as storageDoc, serverTimestamp as storageTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js";
const loginView=document.getElementById('loginView'), dashboardView=document.getElementById('dashboardView'), loginForm=document.getElementById('loginForm'), loginError=document.getElementById('loginError'), logoutBtn=document.getElementById('logoutBtn'), adminUser=document.getElementById('adminUser'), enquiryList=document.getElementById('enquiryList'), searchInput=document.getElementById('searchInput'), statusFilter=document.getElementById('statusFilter'), projectFilter=document.getElementById('projectFilter'), resultCount=document.getElementById('resultCount'), modalBackdrop=document.getElementById('modalBackdrop');
let enquiries=[], selected=null, unsubscribe=null;
const storage=getStorage();
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatDate(timestamp){if(!timestamp)return 'Pending timestamp';const date=timestamp.toDate?timestamp.toDate():new Date(timestamp);return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(date)}
function normaliseStatus(status){return ['new','in-progress','qualified','won','lost'].includes(status)?status:'new'}
function statusLabel(status){return ({new:'New','in-progress':'In progress',qualified:'Qualified',won:'Won',lost:'Lost'})[normaliseStatus(status)]}
function filtered(){const search=searchInput.value.trim().toLowerCase(),status=statusFilter.value,project=projectFilter.value;return enquiries.filter(item=>{const hay=[item.name,item.business,item.email,item.phone,item.project,item.message].join(' ').toLowerCase();return(!search||hay.includes(search))&&(status==='all'||normaliseStatus(item.status)===status)&&(project==='all'||item.project===project)})}
function render(){const rows=filtered();resultCount.textContent=`${rows.length} ${rows.length===1?'enquiry':'enquiries'}`;if(!rows.length){enquiryList.innerHTML='<div class="empty">No enquiries match your filters.</div>';return}enquiryList.innerHTML=rows.map(item=>{const phone=item.phone?`<a href="tel:${escapeHtml(item.phone)}" onclick="event.stopPropagation()">${escapeHtml(item.phone)}</a>`:'<span style="color:#999;font-size:11px">No phone</span>';return `<div class="enquiry-row" data-id="${item.id}"><div class="person"><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(formatDate(item.createdAt))}</small></div><div class="business-cell">${escapeHtml(item.business)}<small>${escapeHtml(item.source||'website')}</small></div><div class="contact-cell"><a href="mailto:${escapeHtml(item.email)}" onclick="event.stopPropagation()">${escapeHtml(item.email)}</a>${phone}</div><div style="font-size:11px">${escapeHtml(item.project||'—')}</div><div><span class="status ${normaliseStatus(item.status)}">${escapeHtml(statusLabel(item.status))}</span></div><div class="row-arrow">↗</div></div>`}).join('');enquiryList.querySelectorAll('.enquiry-row').forEach(row=>row.addEventListener('click',()=>openModal(row.dataset.id)))}
function renderStats(){const count=key=>enquiries.filter(x=>normaliseStatus(x.status)===key).length;document.getElementById('totalCount').textContent=enquiries.length;document.getElementById('newCount').textContent=count('new');document.getElementById('progressCount').textContent=count('in-progress');document.getElementById('wonCount').textContent=count('won')}
function openModal(id){selected=enquiries.find(x=>x.id===id);if(!selected)return;document.getElementById('modalName').textContent=selected.name||'Enquiry';document.getElementById('modalBusiness').textContent=selected.business||'—';document.getElementById('modalProject').textContent=selected.project||'—';const email=document.getElementById('modalEmail');email.textContent=selected.email||'—';email.href=selected.email?`mailto:${selected.email}`:'#';const phone=document.getElementById('modalPhone');phone.textContent=selected.phone||'—';phone.href=selected.phone?`tel:${selected.phone}`:'#';document.getElementById('modalDate').textContent=formatDate(selected.createdAt);document.getElementById('modalSource').textContent=selected.source||'website';document.getElementById('modalMessage').textContent=selected.message||'No message supplied.';document.getElementById('modalStatus').value=normaliseStatus(selected.status);document.getElementById('modalNotes').value=selected.notes||'';document.getElementById('saveMessage').textContent='';modalBackdrop.classList.add('open')}
function closeModal(){modalBackdrop.classList.remove('open');selected=null}
async function verifyAdmin(user){const snap=await getDoc(doc(db,'users',user.uid));return snap.exists()&&snap.data().role==='admin'}
async function loadEnquiries(){if(unsubscribe)unsubscribe();const q=query(collection(db,'enquiries'),orderBy('createdAt','desc'));unsubscribe=onSnapshot(q,snap=>{enquiries=snap.docs.map(d=>({id:d.id,...d.data()}));renderStats();render()},error=>{console.error(error);enquiryList.innerHTML='<div class="empty">Unable to load enquiries. Check your Firebase Security Rules and admin user setup.</div>'})}
loginForm.addEventListener('submit',async event=>{event.preventDefault();loginError.textContent='';try{await signInWithEmailAndPassword(auth,document.getElementById('loginEmail').value.trim(),document.getElementById('loginPassword').value)}catch(error){console.error(error);loginError.textContent='Sign in failed. Check your email and password.'}});logoutBtn.addEventListener('click',()=>signOut(auth));searchInput.addEventListener('input',render);statusFilter.addEventListener('change',render);projectFilter.addEventListener('change',render);document.getElementById('modalClose').addEventListener('click',closeModal);modalBackdrop.addEventListener('click',e=>{if(e.target===modalBackdrop)closeModal()});
document.getElementById('saveBtn').addEventListener('click',async()=>{if(!selected)return;const btn=document.getElementById('saveBtn'),msg=document.getElementById('saveMessage');btn.disabled=true;msg.textContent='Saving…';try{await updateDoc(doc(db,'enquiries',selected.id),{status:document.getElementById('modalStatus').value,notes:document.getElementById('modalNotes').value.trim(),updatedAt:serverTimestamp()});msg.textContent='Saved'}catch(error){console.error(error);msg.textContent='Could not save'}btn.disabled=false});
document.getElementById('deleteBtn').addEventListener('click',async()=>{if(!selected)return;if(!confirm('Delete this enquiry permanently?'))return;try{await deleteDoc(doc(db,'enquiries',selected.id));closeModal()}catch(error){console.error(error);alert('Could not delete this enquiry.')}});
function showLogin(message=''){loginView.hidden=false;loginView.style.display='grid';dashboardView.hidden=true;dashboardView.style.display='none';logoutBtn.hidden=true;adminUser.textContent='';if(message)loginError.textContent=message}
function showDashboard(user){loginView.hidden=true;loginView.style.display='none';dashboardView.hidden=false;dashboardView.style.display='block';logoutBtn.hidden=false;adminUser.textContent=user.email||''}
onAuthStateChanged(auth,async user=>{if(!user){showLogin();if(unsubscribe){unsubscribe();unsubscribe=null}return}try{const allowed=await verifyAdmin(user);if(!allowed){await signOut(auth);showLogin('This account is not authorised for the PRAXIS admin area.');return}showDashboard(user);loginError.textContent='';await loadEnquiries()}catch(error){console.error(error);if(unsubscribe){unsubscribe();unsubscribe=null}await signOut(auth);showLogin('Admin access could not be verified. Check your Firestore users document and Security Rules.')}});


// PRAXIS resource library — admin upload / delete
const resourceForm=document.getElementById('resourceForm');
const adminResourceList=document.getElementById('adminResourceList');
const resourceUploadMessage=document.getElementById('resourceUploadMessage');
const resourceUploadBtn=document.getElementById('resourceUploadBtn');
const resourcePublished=document.getElementById('resourcePublished');
function resourceEsc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function resourceDate(t){if(!t)return '';const d=t.toDate?t.toDate():new Date(t);return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
async function loadResources(){if(!adminResourceList)return;try{const snap=await getDocs(collection(db,'resources'));const items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));if(!items.length){adminResourceList.innerHTML='<div class="empty">No resources uploaded yet.</div>';return;}adminResourceList.innerHTML=items.map(x=>`<div class="admin-resource-row"><div><strong>${resourceEsc(x.title||x.fileName)}</strong><small>${resourceEsc(x.category||'Resource')} · ${resourceEsc(x.fileName||'')} · ${resourceDate(x.createdAt)}</small></div><span class="resource-status ${x.published?'published':'draft'}">${x.published?'Published':'Draft'}</span><a href="${resourceEsc(x.downloadUrl)}" target="_blank" rel="noopener">Open ↗</a><button class="admin-btn danger resource-delete" data-id="${resourceEsc(x.id)}" data-path="${resourceEsc(x.storagePath||'')}">Delete</button></div>`).join('');adminResourceList.querySelectorAll('.resource-delete').forEach(btn=>btn.addEventListener('click',()=>deleteResource(btn.dataset.id,btn.dataset.path)));}catch(e){console.error(e);adminResourceList.innerHTML='<div class="empty">Unable to load resources. Check Firestore rules.</div>';}}
async function deleteResource(id,path){if(!confirm('Delete this resource permanently?'))return;try{await deleteDoc(doc(db,'resources',id));if(path){try{await deleteObject(ref(storage,path))}catch(storageError){console.warn('Storage object could not be deleted',storageError)}}await loadResources();}catch(e){console.error(e);alert('Could not delete this resource.')}}
resourceForm?.addEventListener('submit',async e=>{e.preventDefault();const file=document.getElementById('resourceFile').files[0];if(!file)return; if(file.size>25*1024*1024){resourceUploadMessage.textContent='Files must be 25MB or smaller.';return;} resourceUploadBtn.disabled=true;resourceUploadMessage.textContent='Uploading…';try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`resources/${crypto.randomUUID()}-${safe}`;const storageRef=ref(storage,path);await uploadBytes(storageRef,file,{contentType:file.type||'application/octet-stream',customMetadata:{uploadedBy:auth.currentUser?.uid||''}});const downloadUrl=await getDownloadURL(storageRef);await addDoc(collection(db,'resources'),{title:document.getElementById('resourceTitle').value.trim(),category:document.getElementById('resourceCategory').value.trim(),description:document.getElementById('resourceDescription').value.trim(),fileName:file.name,fileType:file.type||'application/octet-stream',fileSize:file.size,storagePath:path,downloadUrl,published:resourcePublished.checked,createdAt:serverTimestamp(),uploadedBy:auth.currentUser?.uid||''});resourceForm.reset();resourcePublished.checked=true;resourceUploadMessage.textContent='Resource uploaded ✓';await loadResources();}catch(e){console.error(e);resourceUploadMessage.textContent=e?.code==='storage/unauthorized'?'Storage denied — check Firebase Storage rules.':'Upload failed. Check Firebase Storage is enabled and try again.';}finally{resourceUploadBtn.disabled=false;}});
const originalShowDashboard=showDashboard; showDashboard=function(user){originalShowDashboard(user);loadResources();};
